import ArgumentParser
import Foundation
import ADAR2Shared

@main
struct ADAR2LintCommand: ParsableCommand {

    static let configuration = CommandConfiguration(
        commandName: "adar2-lint",
        abstract: "Read an .adar file and emit Xcode-compatible warnings/errors for detected structural issues.",
        discussion: """
        Reads a pre-built .adar graph file (generated by ADAR2ModelBuilder or the adar2-lint full-pipeline
        mode), applies rule configuration from .adarconfig, respects adar_disable/adar_enable source
        annotations, and prints diagnostics in the format Xcode's build system understands.

        Typical Xcode Run Script Phase usage (full pipeline):
          "$SRCROOT/.build/release/ADAR2ModelBuilder" "$SRCROOT" "$SRCROOT/.adar" "$SCHEME_NAME"
          "$SRCROOT/.build/release/adar2-lint" \\
              --adar-file "$SRCROOT/.adar/$SCHEME_NAME.adar" \\
              --source-dir "$SRCROOT"

        SPM Build Tool Plugin:
          Add .plugin(name: "ADAR2LintPlugin", package: "ADAR2LintPlugin") to your target.
          The plugin reads .adar/<TargetName>.adar from the package root.
        """
    )

    // MARK: - Arguments

    @Option(name: .long, help: "Path to the .adar JSON file produced by ADAR2ModelBuilder.")
    var adarFile: String

    @Option(name: .long, help: "Root directory of Swift source files to scan for adar_disable/adar_enable annotations.")
    var sourceDir: String

    @Option(name: .long, help: "Path to the .adarconfig file. Defaults to <source-dir>/.adarconfig.")
    var config: String?

    // MARK: - Run

    mutating func run() throws {
        let adarURL  = URL(fileURLWithPath: adarFile)
        let srcURL   = URL(fileURLWithPath: sourceDir)
        let cfgURL   = config.map { URL(fileURLWithPath: $0) }
                    ?? srcURL.appendingPathComponent(".adarconfig")

        // 1. Decode the .adar graph
        let graph = try decodeGraph(from: adarURL)

        // 2. Resolve the bug report
        guard let bugReport = graph.bugReport else {
            print("note: [ADAR] No bug report found in '\(adarFile)'. Re-run ADAR2ModelBuilder to embed one.")
            return
        }

        // 3. Load rule configuration
        let ruleConfig = ADARConfig.load(from: cfgURL)

        // 4. Scan source annotations
        let suppressions = AnnotationScanner.scan(sourceDir: srcURL)

        // 5. Build node index for source location lookup
        let nodeIndex = Dictionary(
            graph.nodes.map { ($0.declaration.id, $0.declaration) },
            uniquingKeysWith: { first, _ in first }
        )

        // 6. Emit diagnostics
        DiagnosticEmitter(report: bugReport, config: ruleConfig, suppressions: suppressions, adarFilePath: adarFile, nodeIndex: nodeIndex).emit()
    }

    // MARK: - Helpers

    private func decodeGraph(from url: URL) throws -> ADARGraph {
        guard FileManager.default.fileExists(atPath: url.path) else {
            // Emit a note (not an error) so the build doesn't fail when .adar hasn't been generated yet.
            print("note: [ADAR] .adar file not found at '\(url.path)'. Run ADAR2ModelBuilder first.")
            throw ExitCode.success
        }
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(ADARGraph.self, from: data)
    }
}
